import { Box, Title } from "@mantine/core";
import Campaign from "components/campaign/Campaign";
import { type NextPage } from "next";
import Head from "next/head";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <Box py="md">
      <Head>
        <title>EmpathAttic</title>
        <meta
          name="description"
          content="Generated by create-t3-app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <Campaign />
    </Box>
  );
};

export default Home;
