name: Staging Deployment

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Run App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            PATH=$PATH:/${{ secrets.SSH_USERNAME }}/.nvm/versions/node/v18.12.1/bin
            cd /root/staging
            git pull origin main
            npm install
            prisma generate
            prisma migrate deploy
            npm run build
            pm2 start 0
    
  
        
        
