name: Staging Deployment

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Deploy Staging
        uses: appleboy/ssh-action@v0.1.6
    
  
        
        
